spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/babit
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false # 트랜잭션 범위 밖에서 지연 로딩 방지 (실무에서는 false 권장)
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: Babit-Secret-Key-202506   #JWT 토큰 서명을 위한 시크릿키
    token:
      access-expiration-time: 3600000     #1hour
      refresh-expiration-time: 86400000   #24hours